const English = {
  R1: 'Please enter valid email',
  R2: 'Password length should be more than 5',
  R3: 'Email not found',
  R4: 'No Account found registered with your email address',
  R5: 'Sign In',
  R6: 'My Brokerage',
  R7: 'Reset Password',
  R8: 'Remember your password?',
  R9: 'Sign in',
  R10: 'Forgot password',
  R11: "If you have forgotten your password, there's no need to worry as we've got you covered. We send password reset instruction on your email.",
  R12: 'OTP verification',
  R13: 'To ensure the security of your account, we will send a One-Time Password (OTP) to your registered email address when you attempt to reset your password.',
  R14: 'OTP',
  R15: 'Submit',
  R16: 'Resend otp in [time] min',
  R17: 'Enter the verification code we just sent to',
  R18: 'Change email address?',
  R19: 'Resend',
  R20: 'Set new password',
  R21: 'Once you have successfully verified your identity using the OTP sent to your registered email address, you will be able to set a new password for your account.',
  R22: 'Reset Now',
  R23: 'Password',
  R24: 'Confirm password',
  R25: 'Welcome back to Reeva',
  R26: 'We are lorem ipsum team dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  R27: 'Email address',
  R28: 'Forgot password?',
  R29: 'or',
  R30: 'Sign up',
  R32: "Don't have an account?",
  R33: 'Send',
  R34: 'First Name',
  R35: 'Last Name',
  R36: 'Phone No.',
  R37: 'Email',
  R38: 'Address',
  R39: 'Already have an account?',
  R40: 'Next Step',
  R41: 'My Brokerage',
  R42: 'Register',
  R43: 'Preferred company address',
  R44: 'Preferred title company',
  R45: 'Supervisor license No',
  R46: 'Please enter valid phone number',
  R47: 'I agree to the',
  R49: 'Password not matching',
  R50: 'License No',
  R51: 'Password not matching',
  R52: 'Please enter first name',
  R53: 'Please enter last name',
  R54: 'Please enter licence',
  R55: 'Please enter phone number',
  R56: 'Please enter password',
  R57: 'Please enter confirm password',
  R58: 'Please enter broker name',
  R59: 'Please enter broker license no ',
  R60: 'Please enter supervisor name ',
  R61: 'Please enter supervisor license no',
  R62: 'Please enter broker address',
  R63: 'Please enter address',
  R64: 'congratulations your new password set successfully',
  R65: 'Now back to',
  R66: ' to continue',
  R67: 'Login',
  R68: 'Broker License No ',
  R69: 'Broker Name',
  R70: 'Supervisor name',
  R71: 'New Contract',
  R72: 'Drafted Contracts',
  R73: 'Email Templates',
  R74: 'Pricing Plans',
  R75: 'Report an Issue',
  R76: 'LogOut',
  R77: 'My Contacts',
  R78: 'Type a message',
  R79: 'Reeva',
  R80: 'Good ',
  R81: 'Remaining ',
  R82: ' contract',
  R83: 'Reeva is typing',
  R84: ' Contract left',
  R85: ' Upgrade now',
  R86: 'My Name is Reeva',
  R87: 'Say Hi Reeva for start',
  R88: 'Hey, ',
  R89: 'Open now!',
  R90: '⏰ With Reeva, you have saved [time]  Minutes drafting this contracts.',
  R91: "Let's draft new",
  R92: 'Change Password',
  R93: 'Edit Profile',
  R94: 'Phone',
  R95: 'Broker Address',
  R96: 'License No',
  R97: 'Supervisor name',
  R98: 'Supervisor Lic. No.',
  R99: 'Broker Info',
  R100: 'Personal',
  R101: 'Delete Account',
  R102: 'Save Changes',
  R103: 'Please select your profile picture',
  R104: 'Save',
  R105: 'Send Template',
  R106: 'Remaining ',
  R107: ' email',
  R108: 'Send',
  R109: 'Drafted Contracts',
  R110: 'Buyer Name :',
  R111: 'Seller Name :',
  R112: 'My Contacts',
  R113: 'Send Offer',
  R114: 'Send Template',
  R115: 'Search Contact',
  R116: 'No Data Found',
  R117: 'No Contacts Found',
  R118: 'No Email Template Found',
  R119: 'Are you sure that you want to delete your account?',
  R120: 'Cancel',
  R121: 'OK',
  R122: 'Are you sure that you want to log out your account?',
  R123: 'Session expired!',
  R124: 'Something went wrong',
  R125: 'Enter old password',
  R126: 'Enter new password',
  R127: 'Confirm new password',
  R128: 'Please enter old password',
  R129: 'Please enter new password',
  R130: 'Subject',
  R131: 'Message',
  R132: 'Report An Issue',
  R133: 'You have something to report? Great, we love feedback!',
  R134: 'Please enter subject',
  R135: 'Please enter message',
  R136: 'Back to Home',
  R137: 'Thank You For Sharing Your Feedback!',
  R138: "We've received your concern, and we are working to resolve them",
  R139: 'Pricing Plans',
  R140: 'Choose this plan',
  R141: 'Current Plan',
  R142: 'You can easily cancel or modify your subscription whenever you want.',
  R143: 'Terms and conditions & Privacy Policy',
  R144: 'Terms & Condition',
  R145: 'Privacy policy',
  R146: ' - ',
  R147: 'Please enter OTP',
  R148: 'To access this feature of Reeva please purchase Pro plan',
  R149: 'Your maximum limit for creating offers for the free plan has been over'
}
export default English
